### ISSUE TITLE
Add MockSensorData

### ISSUE THREAD

**Issue by porglezomp** [FRC1076/FRC1076-2016-Competition#14]
As noted in #13, we're currently returning `null` from one of our mocks because `SensorData` has no mock object. That situation should be improved.

**Comment by claytonrie** [comment]
Should adding a SensorData interface be included in this issue or be a separate issue?

**Comment by a2aaron** [comment]
I've created a MockSensorData object on my fork and will open a PR.

**Comment by porglezomp** [comment]
It's PR #19.

**Comment by a2aaron** [comment]
Fixed by PR #22
