### ISSUE TITLE
Raise and lower the robot lift arm in autonomous

### ISSUE THREAD

**Issue by porglezomp** [FRC1076/FRC1076-2016-Competition#44]
Currently there are no available encoders or limit switches, so we can't actually do it yet

**Comment by a2aaron** [comment]
I'm assuming you want the robot to lower the lift arm at the start of autonomous, then drive under the low bar, and then reraise the arm after drive to the other side.

**Comment by porglezomp** [comment]
We can't fit under the low bar at any point, no matter what we do with the arm. We have to go at the other side.

**Comment by a2aaron** [comment]
From Solomon's email
- Add in the ability to lower the lift arm during autonomous. I have no idea what our center of gravity will be with the lift arm vertical, and if we become tipsy, we will need to lower it in front of us.

**Comment by a2aaron** [comment]
The lift arm starts retracted and vertical. That doesn't seem like it will alter center of gravity too much but I'll check that out for the start of autonomous.

**Comment by a2aaron** [comment]
#57 contains code for this.
